# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn_ota' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_ota

  

  platform :ios, '9.0'
  target 'rn_otaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rn_ota-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_ota-tvOS

  target 'rn_ota-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
